feat : 씬 세팅 캔버스 적용
Rebuild-Studio/Client pull request #104
Opened 2023-10-23 04:06 UTC by parkdh9018

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명

- 씬 설정의 값이 바뀌면 캔버스에 적용되도록 만들었습니다.

### 📡 핵심 기능

- 환경광(환경이미지, 주변광, 직사광) 캔버스에 적용
- 디스플레이(배경컬러, 그리드) 캔버스에 적용
- 반짝임 효과 캔버스에 적용

### 📸 시각 자료(캡처 화면)
- 환경 이미지 변경
![image](https://github.com/Rebuild-Studio/Client/assets/22982297/4ae11822-0ecc-4341-b81c-abab1a22a131)
- 주변광, 배경색 변경
![image](https://github.com/Rebuild-Studio/Client/assets/22982297/6f268f1a-07a0-44a6-bc68-2373ebf0a278)
- 반짝임 효과
 ![image](https://github.com/Rebuild-Studio/Client/assets/22982297/65e75273-34e1-433c-88ea-8a3e7ac27b44)

### 🛠️ 이슈 및 앞으로 할 일

- SSAO 구현이 필요합니다.
- 그리드 관련 스토어 state, action들을 sceneSettingStore로 옮겼습니다.

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [ ] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [ ] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [ ] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [ ] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-10-23 04:09 UTC, parkdh9018 commented on public/hdri/MX_hdr_indoor_3pointLightStudio_01.hdr
hdr파일은 서버에 존재해서 그 파일을 사용하도록 하였습니다.

2023-10-23 04:11 UTC, parkdh9018 commented on src/components/buttons/SwitchButton.tsx
> +
스위치가 보이는 상태에서 스위치 클릭이 아닌 다른 동작들(단축키, 마우스 컨텍스트 메뉴)로 상태가 바뀌면 스위치가 움직이도록 코드를 추가했습니다.

2023-10-23 06:05 UTC, Joong-Sunny commented
HDRI 이미지 토글은 있는데, background toggle은 안보이는 것 같네요

![image](https://github.com/Rebuild-Studio/Client/assets/63194662/a00755e4-6dc0-4780-8eca-b767a75ce9e2)

2023-10-23 06:16 UTC, Joong-Sunny commented
develop땡겨진건가요? develop브랜치에서는 괜찮은데, 현재 브랜치에는 interaction진입시 ui가 깨지는 것 같습니다(공백생김)

![image](https://github.com/Rebuild-Studio/Client/assets/63194662/538e4b64-6fea-41da-b205-62478108f01b)

2023-10-23 06:39 UTC, Joong-Sunny commented
환경강도가 

기본이 0인데 밝게 되네요, 빛을 더 줄일수 있게 바뀌어야 합니다.

기존MX: 디폴트값 1이며 0까지 줄일수 있음, 5까지 늘릴 수 있음
리빌딩MX: 디폴트값 0이며, 더 줄일수 없음, 5까지 늘릴 수 있음

2023-10-23 06:46 UTC, Joong-Sunny requested changes
### 중복된 커밋
동일한 커밋들이 중복되어 있어 변경사항을 확인하기 힘듭니다. rebase해서 올려주시면 더 좋을 것 같습니다.
![image](https://github.com/Rebuild-Studio/Client/assets/63194662/63c4842d-5287-4333-9df3-f954268e53bf)


### 커밋 정리

커밋 18개중 7개가 `merged develop`입니다. rebase시 정리 한번 부탁드립니다

![image](https://github.com/Rebuild-Studio/Client/assets/63194662/295f9711-83d5-428f-96be-2b1d71577539)


### pr분리

fix: 카메라 큐브 위치 조절 + 버그 수정 에 대한 PR 따로 올려주셔도 괜찮을 것 같습니다.

2023-10-23 06:56 UTC, okorion approved these changes

2023-10-23 06:56 UTC, okorion commented on src/store/storeContainer.ts
> +import selectedobjectStore, {
옛 커밋부터 selectedObjectStore가 아니라 selectedobjectStore가 된 거 같네욥 (`o`, `O` 소문자/대문자)
수정해주시면 감사하겠습니다!

2023-10-23 06:56 UTC, okorion commented on src/store/storeContainer.ts
>    selectedObjectStore: selectedobjectStore,
selectedobjectStore, selectedObjectStore 수정해주시면 감사하겠습니닷

2023-10-23 06:56 UTC, okorion commented
conflicts도 해결해주세요!

2023-10-23 10:19 UTC, parkdh9018 reviewed
리뷰 반영한 수정사항 입니다.
- 백그라운드 색깔 토글 기능
- 환경강도 슬라이더 값 수정
- storeContainer의 SelectedObjectProps 이름 수정
- rebase 진행

rebase의 경우 한번도 사용해보지 않았는데 다음부터는 dev로 부터 pull을 받을때마다 진행하면 되는걸까요?

2023-10-23 11:00 UTC, Joong-Sunny commented
@parkdh9018  그러네요... 이미 다 커밋이 쌓여버려서 어렵겠네요. 그리고 다시 생각해보니 git pull시 rebase에 대한 옵션은 팀 내적으로 협의한바가 없네요. 이번에 붙이시고 다음에 컨벤션 이야기가 되면, 그때부터 rebase로 붙이는게 더 나을 것 같네요

2023-10-23 11:02 UTC, Joong-Sunny commented
background toggle기능은 안보이는 것 같은데, 반영 되었나용

![image](https://github.com/Rebuild-Studio/Client/assets/63194662/b0fdb267-7916-49aa-bd4f-b0ccecb27e46)

2023-10-23 11:08 UTC, Joong-Sunny commented
캔버스 왼쪽 하단의 svg들이 계속 활성화(mx 형광색)색상을 가지고 있는데 의도하신건가요

<img width="327" alt="image" src="https://github.com/Rebuild-Studio/Client/assets/63194662/fd52872a-53d3-4ab4-be1c-f29676bd3f4b">

2023-10-23 11:39 UTC, parkdh9018 commented
> 캔버스 왼쪽 하단의 svg들이 계속 활성화(mx 형광색)색상을 가지고 있는데 svg색상 동작이 이상한 것 같습니다.
> 
> <img alt="image" width="327" src="https://user-images.githubusercontent.com/63194662/277317550-fd52872a-53d3-4ab4-be1c-f29676bd3f4b.png">

rebase 하면서 실수로 잘못 바꾼듯 합니다. 수정하겠습니다.

2023-10-23 11:41 UTC, parkdh9018 commented
> background toggle기능은 안보이는 것 같은데, 반영 되었나용 아래 (기존mx)의 눈알 클릭하면 background가 보이지 않는 기능입니다
> 
> ![image](https://user-images.githubusercontent.com/63194662/277316090-b0fdb267-7916-49aa-bd4f-b0ccecb27e46.png)

백그라운도 토글 기능이 디스플레이 탭에 빠져 있어서 추가하였습니다.
그런데 저 눈 표시와 스위치가 완전히 동일한 기능을 한다고 생각하면 될까요? 굳이 따로 나누어 둔 이유를 모르겠습니다.

2023-10-23 11:48 UTC, Joong-Sunny commented on src/three_components/common/SceneEnvironment.tsx
> +        <Environment background={hdriToggle} blur={hdriIntensity / 5}>
HDRI intensity를 조절했음에도 불구하고 환경광의 강도가 바뀌지 않습니다.
blur를 통해 이미지의 흐림도가 아닌, opacity를 조절함으로써 HDRI내의 오브젝트가 받는 광량을 조절할 수 있게 바뀌어야 할 것 같습니다

2023-10-23 11:48 UTC, Joong-Sunny commented on src/three_components/common/SceneEnvironment.tsx
> +              opacity={1}
이부분을 바꾸면 될 것 같습니다


```javascript
//before
opacity = {1}

//after
opacity = {hdriIntensity}
```

2023-10-23 11:48 UTC, Joong-Sunny commented on src/three_components/common/SceneEnvironment.tsx
> +      ></directionalLight>
self-closing tag로 바꿔주시면 더 좋을 것 같습니다

2023-10-23 11:48 UTC, Joong-Sunny commented on src/components/TopBar.tsx
> +}
'TopBarProps' is declared but never used로 인해, 프로젝트가 build가 되지 않습니다.

( `npm run build` 실행시 오류 )

2023-10-23 12:18 UTC, Joong-Sunny commented on src/three_components/common/Grid.tsx
> +            <gridHelper args={[50, 10, , gridColor.black]} />
colorCenterLine에 대한 인자가 빠져있는 것 같습니다. 명시적으로 값을 넣어주어야 혼란이 적을 거 ㅅ같습니다

2023-10-23 12:18 UTC, Joong-Sunny commented on src/store/sceneSettingStore.ts
> +  setDirectionalLightColor: (state: HsvaColor) => void;
setAmbientLightColor, setDirectionalLightColor등은 쓰이는 곳이 없는 것 같습니다.
추후 사용예정이 있나요

2023-10-23 12:20 UTC, Joong-Sunny commented
@parkdh9018  intensity를 바꾸면 큐브에 받는 광량이 바뀝니다. 
미묘하고 오묘한 차이가 있는데, 내일 같이 보시죠

- 눈알버튼을 조작하면 => 광량은 그대로 유지한 채, hdri배경이미지만 없어지거나 보임
- switch를 조작하면 => 배경이미지와 오브젝트들이 받는 광이 모두 없어지거나 보임

2023-10-24 09:35 UTC, parkdh9018 commented
커밋 정리하고 리뷰해주신 내용에 맞게 기능을 추가하였습니다.
슬라이더 비활성화의 경우 슬라이더 자체에 비활성화 기능이 존재하지 않아 추가하지는 못했습니다.
이것은 이슈로 등록하면 될까요?

2023-10-24 13:20 UTC, Joong-Sunny requested changes

2023-10-24 13:20 UTC, Joong-Sunny commented on src/three_components/common/SceneEffect.tsx
> +      )}
```javascript
{bloomToggle && <Bloom ...>}
```
으로 표현 가능 할 것 같습니다

2023-10-24 13:20 UTC, Joong-Sunny commented on src/three_components/common/SceneEnvironment.tsx
> +  } = sceneSettingStore;
다른 컴포넌트와 컨벤션을 맞춰서 storeContainer에서 sceneSettingStore를 한번 받아와서 다시 쓰는건 어떨까요?

2023-10-24 13:20 UTC, Joong-Sunny commented on src/store/sceneSettingStore.ts
> +  hdriToggle: false,
초기값 true가 되어야 합니닷

2023-10-24 13:30 UTC, Joong-Sunny commented on src/components/common/RightPanel/sceneSetting/HdriSetting.tsx
> +          <img
혹시 모르니 alt 넣어주면 좋을 것 같습니다

2023-10-24 13:33 UTC, Joong-Sunny requested changes
백그라운드 컬러 토글시, 환경이미지가 없어져버리는 이슈가 있습니다.

재현:
- 환경광-환경이미지 켜기
- 디스플레이- background color를 토글링 한두번하고 off로 만듬
- 환경광 탭으로 돌아오기
- 환경이미지가 켜져있다고 뜨지만 환경이미지는 아무것도 보여주지 않음

2023-10-24 13:36 UTC, Joong-Sunny commented
> 커밋 정리하고 리뷰해주신 내용에 맞게 기능을 추가하였습니다. 슬라이더 비활성화의 경우 슬라이더 자체에 비활성화 기능이 존재하지 않아 추가하지는 못했습니다. 이것은 이슈로 등록하면 될까요?

넵,  이슈 두개 따로 올려주시면 될 것 같습니다.
1. 슬라이더 disable 기능추가
2. hdri토글에 따른 슬라이더 disable기능 추가하기

2023-10-25 01:25 UTC, parkdh9018 commented on src/three_components/common/SceneEffect.tsx
> +      )}
이 컴포넌트를 사용하기 위해 필요한 EffectComposer에서 타입 지정을 해주지 않았는지 typescript에러가 나서 이런 형태로 적을 수 밖에 없을 것 같습니다. 
![image](https://github.com/Rebuild-Studio/Client/assets/22982297/5b2b7607-d9ae-4880-9e5e-a51c47edd93a)

2023-10-25 01:44 UTC, parkdh9018 commented on src/three_components/common/SceneEnvironment.tsx
> +  } = sceneSettingStore;
수정하겠습니다.

2023-10-25 01:44 UTC, parkdh9018 commented on src/store/sceneSettingStore.ts
> +  hdriToggle: false,
수정하겠습니다.

2023-10-25 01:46 UTC, parkdh9018 commented on src/components/common/RightPanel/sceneSetting/HdriSetting.tsx
> +          <img
수정하겠습니다.

2023-10-25 05:01 UTC, Joong-Sunny commented on src/three_components/common/SceneEffect.tsx
> +      )}
아하... 감사합니다!

2023-10-25 05:34 UTC, parkdh9018 commented on src/three_components/common/Scene.tsx
> +        }
인라인으로 바꿨다가 다시 styled-componet로 수정했습니다.

2023-10-25 06:25 UTC, Joong-Sunny approved these changes
고생 정말 많으셨습니다 ㅠㅠ

conflict 잡고 머지해주시면 될 것 같습니다👏👏

2023-10-25 06:25 UTC, parkdh9018 commented
> 고생 정말 많으셨습니다 ㅠㅠ
> 
> conflict 잡고 머지해주시면 될 것 같습니다👏👏

중선님이 더 고생많으셨습니다. 세세하게 확인해주셔서 감사합니다.

2023-10-25 07:20 UTC, merged