Feat/hierarchy context menu
Rebuild-Studio/Client pull request #131
Opened 2023-10-24 05:34 UTC by kjh9589

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명

-  계층 구조 contextMenu 추가
-  계층 구조 feature로 분리
-  계층 구조 다중 선택 기능 추가
-  다중 선택 시 하나라도 숨기기 기능 되어 있으면 그룹화 불가 및 전부 보이기 기능 추가
-  copyObject 시 userData 복사 추가
close #129 

### 📡 핵심 기능

- 계층 구조 contextMenu 추가

### 📸 시각 자료(캡처 화면)

![image](https://github.com/Rebuild-Studio/Client/assets/85272794/22434f86-1e24-48cb-92f1-15c0beded601)
![image](https://github.com/Rebuild-Studio/Client/assets/85272794/25635759-c1cd-4f85-8942-1b0fb5207148)

### 🛠️ 이슈 및 앞으로 할 일

- 로딩 컴포넌트 구현

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [ ] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [ ] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [ ] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [ ] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-10-24 07:41 UTC, junman95 commented on src/features/hierarchy/utils/onContextMenuHierarchyEvent.ts
> +  onClickHierarchyEvent(rootObject ? (rootObject as THREE.Mesh) : mesh);
`rootObject !! mesh`
nullish체크로 코딩 가능하지 않을까여?

2023-10-24 07:43 UTC, junman95 commented on src/features/hierarchy/utils/onContextMenuHierarchyEvent.ts
> +  const rootObject = findRootGroup(mesh) || findRootAsset(mesh);
해당 피처와는 관련은 없지만, 위 두 find 함수들은 null이 아닌 undefined를 내보내도록 하신 이유가 있을까요?

2023-10-24 07:44 UTC, junman95 commented on src/three_components/utils/executeContextMenu.ts
> +          primitiveStore.updatePrimitive(key, value);
과거에는 value를 클론했던 이유가 무엇인가요?

2023-10-24 07:58 UTC, junman95 commented on src/store/contextMenuStore.ts
> +      switch (res[i][0]) {
함수를 쭉 봤는데, 대충 context메뉴 구성을 하는 시선의 흐름과 동일하게 작성되어 좋았던것 같으나,
코드 변경만을 봤을때, res , i 등 모호한 변수명은 코드를 읽어내는데에 다소 어려움이있었습니다.
`res -> resContextMenuItems`
for 루프는 forEach를 통해서 가독성을 높일 수 있지 않을까 싶습니다.
```
res.forEach(([contextMenuType, ,], index) => {
      switch (contextMenuType) {
        case "그룹": {
          res[index][2] = false;
          break;
        }
      }
    });
```

2023-10-24 08:01 UTC, wildcatco requested changes

2023-10-24 08:01 UTC, wildcatco commented on src/features/hierarchy/components/HierarchyElement.tsx
> +  const isInteractionVisible = () => {
const isInteractionVisible = mesh.name !== "GROUP" && mesh.name !== "ASSET"
이렇게 간단히 표현 가능해보입니다

2023-10-24 08:04 UTC, wildcatco commented on src/features/hierarchy/components/HierarchyElement.tsx
> +  const isInteractionVisible = () => {
!["GROUP", "ASSET"].includes(mesh.name)

2023-10-25 01:25 UTC, kjh9589 commented on src/features/hierarchy/components/HierarchyElement.tsx
> +  const isInteractionVisible = () => {
어제 구두로 전달해드렸습니다.
주석을 추가하도록 하겠습니다.

2023-10-25 01:25 UTC, kjh9589 commented on src/store/contextMenuStore.ts
> +  if (isInVisible) {
좀더 정확하게 변수명 만들겠습니다

2023-10-25 01:26 UTC, kjh9589 commented on src/store/contextMenuStore.ts
> +      switch (res[i][0]) {
foreach로 바꾸겠습니다

2023-10-25 01:26 UTC, kjh9589 commented on src/three_components/utils/executeContextMenu.ts
> +          primitiveStore.updatePrimitive(key, value);
구두로 전달해드렸습니다.

2023-10-25 01:39 UTC, wildcatco reviewed
s

2023-10-25 01:39 UTC, wildcatco commented on src/features/hierarchy/utils/onContextMenuHierarchyEvent.ts
> +import onClickHierarchyEvent from "./onClickHierarchyEvent";
df

2023-10-25 01:39 UTC, wildcatco commented on src/features/hierarchy/utils/onContextMenuHierarchyEvent.ts
> +  mesh: THREE.Mesh
ddd

2023-10-25 01:39 UTC, wildcatco approved these changes

2023-10-25 07:33 UTC, junman95 approved these changes

2023-10-25 07:48 UTC, merged