style: SwitchButton 너비 변경
Rebuild-Studio/Client pull request #134
Opened 2023-10-24 07:17 UTC by wildcatco

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명

- close #114 

### 📡 핵심 기능

- SwitchButton 컴포넌트의 너비 변경 (100% 차지하지 않도록)
- SwitchButton의 위치 조정

### 📸 시각 자료(캡처 화면)
<img width="240" alt="1-before" src="https://github.com/Rebuild-Studio/Client/assets/53351097/7eff0328-6f22-4a6c-a94c-37f00d7369b7">
<img width="240" alt="1-after" src="https://github.com/Rebuild-Studio/Client/assets/53351097/f6d0389e-2e08-40f0-bbe1-26f53522702d">
<br>

<img width="231" alt="2-before" src="https://github.com/Rebuild-Studio/Client/assets/53351097/816ff7e4-35f1-4455-a0bb-07ecfc30c14e">
<img width="231" alt="2-after" src="https://github.com/Rebuild-Studio/Client/assets/53351097/89320bf9-f7a1-415c-9020-0293e049ad92">
<br>

<img width="236" alt="3-before" src="https://github.com/Rebuild-Studio/Client/assets/53351097/2136a0f5-c7ac-46b5-8283-d2e181321e12">
<img width="236" alt="3-after" src="https://github.com/Rebuild-Studio/Client/assets/53351097/8051479e-de87-43dc-afa8-a1364ca91fe6">

### 🛠️ 이슈 및 앞으로 할 일

- 

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [ ] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [ ] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [ ] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [ ] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-10-24 07:22 UTC, okorion approved these changes
확인했습니다!

2023-10-24 13:50 UTC, Joong-Sunny requested changes
추가적으로... prop으로 disable 받을 수 있도록 추가해줄 수 있나요? 자주 쓰일 것 같아요

2023-10-24 13:50 UTC, Joong-Sunny commented on src/components/buttons/SwitchButton.tsx
> +        <SwitchLever $checked={isChecked} onClick={handleSwitchChange} />
isChecked를 사용하지 않고 checked를 사용하는게 어떨까요?
외부에서 주입해준 chekced의 상태변화에 따라 스위치의 상태가 변해야 한다고 생각합니다.

e.g) 하나의 스위치를 토글링하면 다른 스위치가 꺼져야 하는 상황 등

2023-10-24 22:51 UTC, wildcatco commented on src/components/buttons/SwitchButton.tsx
> +        <SwitchLever $checked={isChecked} onClick={handleSwitchChange} />
@Joong-Sunny 외부에서 준 checked는 체크박스의 초기상태만 나타내주고 그 이후 변화는 체크박스에서 상태관리하는 방식인데 상태 관리를 컴포넌트 밖으로 빼자는 말 맞나요?
(예제의 방식은 radio로 구현해야 합니다)

2023-10-24 22:53 UTC, wildcatco commented
@Joong-Sunny  별개의 pr로 올리겠습니다!

2023-10-25 00:54 UTC, Joong-Sunny approved these changes

2023-10-25 00:55 UTC, merged