refactor: prettier 설정, 파일 이름 변경
Rebuild-Studio/Client pull request #164
Opened 2023-10-26 12:25 UTC by wildcatco

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명

- close #126 

### 📡 핵심 기능

- prettier 설정
```json
{
  "printWidth": 80,
  "singleQuote": true,
  "trailingComma": "none",
  "tabWidth": 2
}
```
- import 순서 정렬 설정
```js
{
"plugins": ["@trivago/prettier-plugin-sort-imports"],
  "importOrder": [
    "^react$",
    "^three$",
    "^mobx(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@/(.*)$",
    "^@components/(.*)$",
    "^@pages/(.*)$",
    "^@store/(.*)$",
    "^@hooks/(.*)$",
    "^@utils/(.*)$",
    "^@network/(.*)$",
    "^@resources/(.*)$",
    "^@assets/(.*)$",
    "^@stories/(.*)$",
    "^./",
    "^../"
  ],
  "importOrderSortSpecifiers": true // 같은 그룹 내 알파벳 순서 정렬
}
```
- 파일 이름 변경 (filename.type.확장자)

### 📸 시각 자료(캡처 화면)

### 🛠️ 이슈 및 앞으로 할 일

- 

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [ ] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [ ] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [ ] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [ ] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-10-26 12:37 UTC, wildcatco commented
@Joong-Sunny 하나하나 봐주세요

2023-10-26 13:18 UTC, okorion approved these changes
문제 없이 돌아가길! 🙏 LGTM!

2023-10-26 13:29 UTC, Joong-Sunny commented
@wildcatco typo 변경 커밋 하나 끼얹었습니다

2023-10-26 14:26 UTC, junman95 requested changes
빌드 이슈 해요

2023-10-26 14:35 UTC, Joong-Sunny commented
@junman95 
#160 에서 원래 빌드 안되었는데 다같이 머지하기로 한거 아니였나요
[preview chromatic build](https://github.com/Rebuild-Studio/Client/actions/runs/6651509184/job/18073673033)
[preview ci build](https://github.com/Rebuild-Studio/Client/actions/runs/6651508690/job/18073671979)

2023-10-26 14:43 UTC, junman95 commented
> @junman95 #160 에서 원래 빌드 안되었는데 다같이 머지하기로 한거 아니였나요 [preview chromatic build](https://github.com/Rebuild-Studio/Client/actions/runs/6651509184/job/18073673033) [preview ci build](https://github.com/Rebuild-Studio/Client/actions/runs/6651508690/job/18073671979)

단순히 tsc 이슈라고 생각했었는데, 레포자체가 내부망에 설치되었다는 것을  간과하고 있었네요.

2023-10-26 14:50 UTC, Joong-Sunny commented
1. 클론해서 aws artifact 올리거나
2. core소스코드 압축해서 저희 래포에 올리는거 

어때요? 물론 잘 될지는 뇌피셜입니다.

2023-10-26 14:51 UTC, Joong-Sunny commented
내일 체육대회? 하면서 심심하면 다같이 맞짱토론 해보시죠

2023-10-26 14:52 UTC, Joong-Sunny commented
혼틈 하클도 전 찬성이긴 해요

2023-10-26 14:56 UTC, Joong-Sunny commented
free tier 는 10만번 요청 꽁짜이고
요청당 가격은 아래라고 하는데, 전 막상 돌리면 항상 훨씬 많이 나오는 것 같습니당

![image](https://github.com/Rebuild-Studio/Client/assets/63194662/d7f763c3-bb15-4152-b4e5-f8be9812b5af)

![image](https://github.com/Rebuild-Studio/Client/assets/63194662/2a875f41-3af9-4502-94d4-caea98e3101e)

2023-10-30 03:15 UTC, junman95 approved these changes

2023-10-30 03:21 UTC, merged