Feat/history updates
Rebuild-Studio/Client pull request #173
Opened 2023-10-30 06:41 UTC by parkdh9018

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명

- 머터리얼 관련 히스토리 로직 추가하였습니다.

### 📡 핵심 기능
- 머터리얼 요소, 색상, 금속성, 거칠기 수정 시 히스토리에 기록 됩니다.
- InputFiled로 트랜스포메이션(위치, 회전, 크기) 수정 시  히스토리에 기록 됩니다.
- 머터리얼 까지 복사할 수 있는 함수를 사용하여 스냅샷을 찍도록 하였습니다. 

### 📸 시각 자료(캡처 화면)

### 🛠️ 이슈 및 앞으로 할 일

- 씬 세팅의 내용 변경 시 히스토리 추가
- [renderObjects](https://github.com/Rebuild-Studio/Client/blob/feat/historyUpdates/src/three_components/utils/renderThreeComponents.tsx#L62)함수의 타입 지정이 필요
- 히스토리 관련 단축키 지정 필요

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [ ] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [ ] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [ ] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [ ] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-10-31 00:33 UTC, wildcatco requested changes
https://github.com/Rebuild-Studio/Client/assets/53351097/d118f7bb-487c-4405-91cd-94dc6e787908


금속성 변경하고 거칠기 변경하면 히스토리가 제대로 작동 안하는거 같습니다

2023-10-31 00:40 UTC, wildcatco commented on src/three_components/utils/renderThreeComponents.tsx
> +  // TODO : store 타입 필요
PrimitiveStore 클래스를 import해와서 타입으로 사용하면 될거같습니다

2023-10-31 01:02 UTC, jeongwoolee3 commented
![image](https://github.com/Rebuild-Studio/Client/assets/66979594/903e3848-f20e-4b7c-b1fc-ce0a8c296762)

히스토리 너무 많아지면 overflow 처리 해주시는것도 좋을것같습니다

2023-10-31 01:08 UTC, parkdh9018 commented
> ![image](https://user-images.githubusercontent.com/66979594/279228958-903e3848-f20e-4b7c-b1fc-ce0a8c296762.png)
> 
> 히스토리 너무 많아지면 overflow 처리 해주시는것도 좋을것같습니다

#179
수정하겠습니다.

2023-10-31 01:18 UTC, wildcatco commented on src/components/layout/CanvasLeftPanel/historyPanel/HistoryPanel.tsx
> +              key={nanoid()}
nanoid를 key값으로 사용하면 안됩니다.(https://github.com/ai/nanoid#react)

2023-10-31 02:13 UTC, parkdh9018 commented on src/components/layout/CanvasLeftPanel/historyPanel/HistoryPanel.tsx
> +              key={nanoid()}
아예 하지 말라고 명시되어 있네요. 수정하겠습니다.

2023-11-03 05:47 UTC, jeongwoolee3 approved these changes

2023-11-06 04:44 UTC, Joong-Sunny commented
close issue due to the gitlab이민

2023-11-06 04:44 UTC, closed without merging