Fix/color picker position
Rebuild-Studio/Client pull request #186
Opened 2023-10-31 10:56 UTC by jeongwoolee3

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명
#close 166
#close 144 
- 패널 overflow 설정을 안하면  #166 문제 발생
- overflow 설정을하면 자식으로있는 메뉴판들이 모두 hidden 처리됨
- ReactDOM.createPortal 써서 처리 
- createMenu에서 anchor버튼 분리

### 📡 핵심 기능

- Menu에서 버튼 분리
- index에 menu-root 만들어서 menu컴포넌트 portal처리

### 📸 시각 자료(캡처 화면)

![image](https://github.com/Rebuild-Studio/Client/assets/66979594/559b916b-07ee-48be-93e9-8e1808193e74)

### 🛠️ 이슈 및 앞으로 할 일

-  인터렉션 안되는거 테스트 
- 에셋클릭시  쉐이프탭에서 오류 , 빛 머테리얼 조정 속성 

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [x] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [x] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [x] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [x] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-11-01 03:58 UTC, parkdh9018 commented
![image](https://github.com/Rebuild-Studio/Client/assets/22982297/de5508dd-eb94-4b70-89da-d4d9187745c8)
컬러 피커가 창이 작으면 글자들이 잘리는 이슈가 있습니다.

2023-11-01 04:02 UTC, parkdh9018 commented
![image](https://github.com/Rebuild-Studio/Client/assets/22982297/620726b8-0849-454e-9f90-4183e184b207)
씬 세팅쪽의 컬러 피커 부분도 수정이 필요합니다.

2023-11-01 08:41 UTC, parkdh9018 approved these changes

2023-11-02 06:49 UTC, wildcatco requested changes
현재 pr에서 하고있는 일이 많은데 다음부터 쪼개서 올려주시면 리뷰하기 편할거 같습니다!

2023-11-02 06:49 UTC, wildcatco commented on src/components/common/RightPanel/LightProperty.tsx
> +        {ReactDOM.createPortal(
계속 중복되는 코드 같은데 컴포넌트화 해주면 좋을거같아요

2023-11-02 07:55 UTC, jeongwoolee3 commented on src/components/common/RightPanel/LightProperty.tsx
> +        {ReactDOM.createPortal(
넵~! 수정했습니당

2023-11-02 08:30 UTC, wildcatco approved these changes

2023-11-03 04:56 UTC, merged