변수노드-넘버(variableNumberNode) 사용 시 터지는 문제 해결=>Mui Input color 속성 문제로 확인.
Rebuild-Studio/Client pull request #197
Opened 2023-11-02 07:18 UTC by okorion

## 📌 `Pull Request` 관련 내용 공유

### 📋 PR 설명

- 변수노드-넘버(variableNumberNode) 사용 시 터지는 문제 해결

### 📡 핵심 기능

- ThemeProvider, createTheme를 활용하여 Mui Input 속성 추가

### 📸 시각 자료(캡처 화면)
![image](https://github.com/Rebuild-Studio/Client/assets/97646070/53c0234a-72c4-4617-80c5-72dc07f3c2fc)

### 🛠️ 이슈 및 앞으로 할 일

- 노드에 한글만 입력되는 버그 발견. 추후 논의 후 해결 예정.

<br>

## 🤖 `PR` 셀프 체크리스트 🤖

> 코드 확인 후 `[ ]`사이 공백을 `x`로 체크하시오

<br>

### ⌨️ 코드 컨벤션!

- [x] 불필요한 console 디버깅 코드는 제거했나요? (스토리북 예외)
    - `console.log(selectedObject[0])`

- [x] 변수명 혹은 파일명이 너무 추상적이지는 않나요?
  - `setType` -> `setBackgroundColorType ` 

- [x] 불필요한 공백을 제거하셨나요?

    - ```react
      <AppWrapper>
        <MenuBar />
        <Scene />
                          // <- X
      </AppWrapper>
      ```

- [x] 불필요한 주석을 제거하셨나요?

    - ```react
      // primitiveStore.addPrimitive(                          // <- X
      //   storeId,                                            // <- X
      //   renderSelectedGroup(storeId, mesh.clone())          // <- X
      // );                                                    // <- X
      ```

<br>

2023-11-02 07:52 UTC, Joong-Sunny approved these changes
LGTM

2023-11-03 00:13 UTC, wildcatco requested changes

2023-11-03 00:13 UTC, wildcatco commented on src/interaction(legacyJS)/src/Components/views/02. Studio/04. EventPanel/node/Header/UxSelector.jsx
> +        </ThemeProvider>
이미 sx로 스타일을 커스텀해주고 있어서 theme은 필요하지않아 보입니다.

그냥 color값만 제거하고
```js
<Input
  onChange={handleSelectorChange}
  sx={style.Input}
  placeholder="MY_KEY"
  value={node.uxSelector}
/>
```
이렇게 넣어줘도 될거같습니다

2023-11-03 00:16 UTC, wildcatco commented on src/interaction(legacyJS)/src/Components/views/02. Studio/04. EventPanel/node/Header/UxSelector.jsx
> +        </ThemeProvider>
원래 터졌던이유: color='white'를 넣어주었지만 white라는 custom theme이 없기 때문(따로 정의하지 않으면 primary와 secondary만 존재)
지금 안터지는 이유: ThemeProvider를 넣어주어서가 아니라 color속성을 없앴기 때문

2023-11-03 00:34 UTC, okorion commented on src/interaction(legacyJS)/src/Components/views/02. Studio/04. EventPanel/node/Header/UxSelector.jsx
> +        </ThemeProvider>
엇 input 밑줄을 흰색으로 바꾸고 싶은데 themeprovider 지우면 흰색으로 못 넣지 않나요??

2023-11-03 00:35 UTC, okorion commented on src/interaction(legacyJS)/src/Components/views/02. Studio/04. EventPanel/node/Header/UxSelector.jsx
> +        </ThemeProvider>
자세한 설명 감사합니닷 🫡

2023-11-03 01:10 UTC, wildcatco commented on src/interaction(legacyJS)/src/Components/views/02. Studio/04. EventPanel/node/Header/UxSelector.jsx
> +        </ThemeProvider>
아아 맞습니다. 넘버쪽 인풋인줄 알고 어차피 라인 없길래 빼도 되는줄 알았네요. 이대로 붙히면 될거같아요~

2023-11-03 01:11 UTC, wildcatco approved these changes

2023-11-03 01:41 UTC, merged