Feat/right panel
Rebuild-Studio/Client pull request #32
Opened 2023-09-22 09:50 UTC by jeongwoolee3

- 트랜스폼 조절시 렌더링 싱크 안맞는 문제 해결
- 오른쪽 패널 좀 더 이쁘게 UI 구성
- 금속성, 거칠기 slider연동
- 머테리얼 요소 타입 선택 -> 오브젝트 적용
- 머테리얼 이미지 메뉴판 구현

Todo
쉐이더, 오브젝트 컬러 픽커

2023-09-25 01:13 UTC, parkdh9018 commented on src/three_components/MaterialLoader.tsx
> +});
리턴하는 컴포넌트가 없다면 RenderScene.tsx에 이 로직이 들어가면 어떨까요?

2023-09-25 02:03 UTC, kjh9589 commented on src/components/common/InputField.tsx
> +const updateTransform = (prop: string, newValue: any, newMesh: THREE.Mesh) => {
any를 안 받기 위해 value별 함수를 만들고 그 바깥에서 prop을 switch case로 하면 가능하지 않을까요?
switch(prop) {
 case "postion":
     updateTransformPosition(newValue: THREE.Vector3, newMesh: THREE.Mesh

2023-09-25 03:53 UTC, kjh9589 commented on src/components/common/RightPanel/MaterialData.ts
> +const data_store = observable({
카멜로 바꿔주세요.

2023-09-25 03:56 UTC, kjh9589 commented on src/components/common/RightPanel/MaterialData.ts
> +  mat_tex_list: [
카멜로 바꿔주시고 그냥 materialTextureList라고 쓰셔도 될 것 같아요
길어져도 괜찮으니 가능하면 그냥 풀어서 적어주세요.

2023-09-25 03:58 UTC, kjh9589 commented on src/components/common/RightPanel/RightPanel.tsx
>      const keys = Object.keys(selectedPrimitives);
keys를 어디서 사용하는건가요?

2023-09-25 03:59 UTC, parkdh9018 commented on src/components/common/RightPanel/MaterialData.ts
> +  mat_tex_list: [
아래의 데이터들은 변하지 않는 값들이니 observer가 아닌 상수로 빼도 되지 않을까요?

2023-09-25 04:00 UTC, kjh9589 commented on src/components/common/Slider.tsx
> +  { property: string; materialType: any }
materialType은 명세할 수가 없나요?

2023-09-25 04:01 UTC, kjh9589 commented on src/components/common/Slider.tsx
> +        (mesh.material as any)[materialProperty.property] = newValue;
any로 타입 단언하는 이유가 뭔가요?

2023-09-25 04:04 UTC, kjh9589 commented on src/store/primitiveStore.ts
> +  selectedMaterial: string;
이곳은 threeComponent, mesh들을 관리하는 곳입니다.
store를 하나 만드시는 게 나을 것 같습니다.

2023-09-25 04:06 UTC, kjh9589 commented on src/store/primitiveStore.ts
> +  setSelectedMaterial: (material: string) => void;
set이 있다면 clear와 쌍으로 만들어주세요
작업이 끝나면 clear를 호출하여 다른 object 선택 시 이전 선택한 값에 영향을 받지 않도록 하기 위해서입니다.

2023-09-25 04:08 UTC, kjh9589 commented on src/store/primitiveStore.ts
> +  selectedMaterial: "MX_mat_defalt_white_01",
사용자가 머티리얼을 선택하지 않아도 항상 이 값이 default라면 머티리얼이 AAA라는 임의의 값으로 설정되어 있는 object인 경우 머티리얼을 선택하지 않고 닫더라도 default 머티리얼이 반영될 일이 없나요?

2023-09-25 04:09 UTC, kjh9589 commented on src/three_components/MaterialLoader.tsx
> +});
네 저도 그렇게 생각합니다.

2023-09-25 04:11 UTC, kjh9589 commented on src/three_components/MaterialLoader.tsx
> +});
RenderScene과 동일 계층에 있어야하는 게 아니라면 저도 그렇게 생각합니다.

2023-09-25 04:26 UTC, jeongwoolee3 commented on src/three_components/MaterialLoader.tsx
> +});
넵 그렇게 수정하겠습니당

2023-09-25 04:27 UTC, jeongwoolee3 commented on src/components/common/RightPanel/MaterialData.ts
> +const data_store = observable({
넵!

2023-09-25 04:27 UTC, jeongwoolee3 commented on src/components/common/RightPanel/MaterialData.ts
> +  mat_tex_list: [
넵!

2023-09-25 04:28 UTC, jeongwoolee3 commented on src/components/common/RightPanel/RightPanel.tsx
>      const keys = Object.keys(selectedPrimitives);
selectedPrimitives에서 key값으로 value(Mesh)에 접근하려고 keys를 사용합니다

2023-09-25 04:57 UTC, jeongwoolee3 commented on src/store/primitiveStore.ts
> +  selectedMaterial: "MX_mat_defalt_white_01",
지금까지는 스토어에 clear가 없어서 전에 선택한 AAA값으로 남아있을거같은데 지금 스토어에 clear만들때 그런경우 까지 고려해서 만들겠습니다. 셀렉티드 오브젝트의 머테리얼값을 가져와서 초기값 설정하는것으로 만들게요~!~!

2023-09-25 05:17 UTC, jeongwoolee3 commented on src/store/primitiveStore.ts
> +  setSelectedMaterial: (material: string) => void;
넵~!

2023-09-25 05:47 UTC, hbk89 commented on src/components/common/Grid.tsx
> +  items: React.ReactNode;
배열에서 단수로 바꼇는데, items인가요?

2023-09-25 05:47 UTC, hbk89 commented on src/components/common/InputField.tsx
> +
inputField 파일 라인이 너무 깁니다.
줄일 수 있는 방안을 연구해보는것 좋을거 같습니다.

2023-09-25 05:47 UTC, hbk89 commented on src/components/common/RightPanel/MaterialTemplate.tsx
> +  outline: ${(props) => (props.isSelected ? "solid 0.15vh #e3f853" : "none")};
outline의 경우 만약 기획에서 공통된 스타일을 가진다면, 공통화 해주시고 아니라면 걍 놔두세용

2023-09-25 05:47 UTC, hbk89 commented on src/components/common/RightPanel/MaterialTemplate.tsx
> +          src={"/icons/rightTab/" + template[1] + ".png"}
아래는 백틱쓰셨는데 이건 왜 백틱이 아닌가요

2023-09-25 05:47 UTC, hbk89 commented on src/components/common/RightPanel/TransFromationInfo.tsx
> -            <div>
map시, key 안넣으면 워닝 뜰겁니다

2023-09-25 07:40 UTC, jeongwoolee3 commented on src/components/common/Grid.tsx
> +  items: React.ReactNode;
Grid니까 먼가 item들을 나열하는 느낌이라 items라고 했는데 items으로 바꾸겠습니다

2023-10-04 05:59 UTC, jeongwoolee3 commented on src/components/common/RightPanel/MaterialTemplate.tsx
> +          src={"/icons/rightTab/" + template[1] + ".png"}
수정했습니다

2023-10-04 06:02 UTC, jeongwoolee3 commented on src/components/common/InputField.tsx
> +
함 쪼개서 반영해보았습니다

2023-10-04 06:02 UTC, jeongwoolee3 commented on src/components/common/RightPanel/TransFromationInfo.tsx
> -            <div>
넵!

2023-10-04 06:25 UTC, junman95 commented
이미지 다운사이징 필요할거같아요

2023-10-04 07:01 UTC, Joong-Sunny requested changes
수고하셨습니다! 👍
커밋이 약 30개인데, 고생하신 변경사항이 쉽게 읽히지 않는 것 같습니다.
커밋을 통합하거나, 관련된 작업끼리 합치는 등의 방식으로 커밋의 수를 줄여주시면 더 좋을것 같습니다. git rebase -i나 git squash를 활용하시면 도움이 될 것 같습니당

2023-10-04 07:50 UTC, jeongwoolee3 commented on src/components/common/RightPanel/ColorHandler.ts
> +  const keys = Object.keys(primitiveStore.selectedPrimitives);
오 넵, 그리고 만약 없더라도, 빈객체로 할당될것같습니다 keys = {} 이렇게요

2023-10-04 07:50 UTC, jeongwoolee3 commented on src/components/common/RightPanel/RightPanel.tsx
> +                <Material
넵 꼼꼼히 봐주셔서 감사합니당~!

2023-10-04 08:08 UTC, Joong-Sunny commented on src/components/common/RightPanel/ColorHandler.ts
> +  const keys = Object.keys(primitiveStore.selectedPrimitives);
아 그러겠네요🙏

2023-10-04 08:30 UTC, junman95 commented on src/components/common/RightPanel/RightPanel.tsx
> +                <Material
어딘가 padding이나 margin 잘못 써서 그럴거 같네요.

2023-10-04 08:40 UTC, jeongwoolee3 commented on src/components/common/RightPanel/RightPanel.tsx
> +                <Material
이게 사실은 GNB가 확장될때 vh가 동적으로 바뀌게되면서 생기는 이슈인데 전역으로 관리하자니, app 파일에서 관리하는건 아닌거 같고, 스토어로 관리하자니 과한거같아서 다른 분들과 얘기해볼 필요가있는것같습니다 전에 Mxstudio에서는 common 스토어로 관리한것같습니다

2023-10-06 05:08 UTC, kjh9589 commented on src/components/common/RightPanel/ColorContent.tsx
> +          {rgbChannels.map((channel) => (
key 설정 안 해줘도 되나요?

2023-10-06 05:10 UTC, kjh9589 commented on src/components/common/RightPanel/ColorContent.tsx
> +        {saturationSilder === true && (
saturationSlider가 boolean형이라면 === true 조건을 사용 안 해도 되지 않을까요

2023-10-06 05:10 UTC, kjh9589 commented on src/components/common/RightPanel/ColorContent.tsx
> +        {brightnessSlider === true && (
brightnessSlider가 boolean형이라면 === true 조건을 사용 안 해도 되지 않을까요

2023-10-06 05:11 UTC, jeongwoolee3 commented on src/components/common/RightPanel/ColorContent.tsx
> +        {brightnessSlider === true && (
마자요~!~! 수정하겠습니다

2023-10-06 05:11 UTC, kjh9589 commented on src/components/common/RightPanel/ColorHandler.ts
> +export function updateMaterialColor(phsva: HsvaColor) {
화살표 함수로 바꿔주세요

2023-10-06 05:12 UTC, kjh9589 commented on src/components/common/RightPanel/ColorHandler.ts
> +export function updateMaterialAlpha(alpha: number) {
화살표 함수로 바꿔주세요

2023-10-06 05:14 UTC, jeongwoolee3 commented on src/components/common/RightPanel/ColorHandler.ts
> +export function updateMaterialAlpha(alpha: number) {
넵

2023-10-06 05:14 UTC, jeongwoolee3 commented on src/components/common/RightPanel/ColorContent.tsx
> +          {rgbChannels.map((channel) => (
설정하겠습니다~

2023-10-06 05:16 UTC, kjh9589 commented on src/components/common/RightPanel/ColorHandler.ts
> +    primitiveStore.selectedPrimitives[keys[0]].material = selectedMaterial;
얕은 복사라 여기까지만 해도 혹시 적용되지 않나요?

2023-10-06 05:18 UTC, kjh9589 commented on src/components/common/RightPanel/ColorHandler.ts
> +export const rgbToHsva = action((rgb: any, opacity: number) => {
라이브러리에서 제공하는 변수를 사용해야하는 거라면 라이브러리에 명세된 타입이 없나요?

2023-10-06 05:19 UTC, kjh9589 commented on src/components/common/RightPanel/ColorPicker.tsx
> +  color: any;
color가 알 수 없게 들어오나요?

2023-10-06 05:21 UTC, kjh9589 commented on src/components/common/RightPanel/MaterialInfo.tsx
> +  const keys = Object.keys(primitiveStore.selectedPrimitives);
0번 째 값만을 가져오기 떄문에
const selectedPrimitive= Object.values(primitiveStore.selectedPrimtives)[0]으로 바꿀 수 있을 것 같습니다.

2023-10-06 05:22 UTC, kjh9589 commented on src/components/common/RightPanel/MaterialTemplate.tsx
> +          key={index}
index말고 다른 것이 key가 될 수 없는 상황인가요?

2023-10-06 05:26 UTC, kjh9589 commented on src/components/common/RightPanel/TransFromationInfo.tsx
> +              <span key={index}>{prop["title"]}</span>
key가 index가 될 수 밖에 없는 상황인가요?

2023-10-06 05:27 UTC, kjh9589 commented on src/components/common/RightPanel/TransFromationInfo.tsx
>            const axes: ("x" | "y" | "z")[] = ["x", "y", "z"];
항상 고정값으로 사용한다면 외부에 한 번만 선언해도 될 것 같습니다.

2023-10-06 05:27 UTC, kjh9589 commented on src/components/common/RightPanel/TransformInput.tsx
> +  currentValue: any;
inputvalue가 number인데 currentValue가 왜 any인가요

2023-10-06 05:30 UTC, kjh9589 commented on src/components/common/RightPanel/TransformInput.tsx
> +    primitiveStore.selectedPrimitives[keys[0]]?.[props.type];
keys의 length를 확인하지 않고 바로 사용하는 걸 보니 value로 바꿀 수 있지 않을까요

2023-10-06 05:31 UTC, kjh9589 commented on src/components/common/RightPanel/TransformInput.tsx
> +  }, [primitiveStore.selectedPrimitives]);
이쪽도 그냥 value사용하면 되지 않을까요

2023-10-06 06:17 UTC, jeongwoolee3 commented on src/components/common/RightPanel/TransformInput.tsx
> +  }, [primitiveStore.selectedPrimitives]);
넵넵@@ 꼼꼼히 봐주셔서 정말 감사합니다 수정사항 반영하여 다시 올리겠습니다

2023-10-06 07:09 UTC, merged